management.endpoints.web.exposure.include: "*"
spring.profiles.active: dev

spring:
  mvc:
      pathmatch:
            matching-strategy: ant_path_matcher       
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#---
#
#spring:
#  profiles: dev
#server:
 # port = 9080  
---

#spring:
#  profiles: prd
#server:
 # port: 9090


